disabled_rules: # rule identifiers to exclude from running
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - todo
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  
